# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-26 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Families',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=50)),
                ('family_description', models.CharField(blank=True, max_length=100, null=True)),
                ('family_date_from', models.DateField(blank=True, null=True)),
                ('family_date_to', models.DateField(blank=True, null=True)),
                ('other_family_details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Individuals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=50)),
                ('other_individual_details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship_Types',
            fields=[
                ('relationship_type_code', models.IntegerField(primary_key=True, serialize=False)),
                ('relationship_type_description', models.CharField(choices=[('C', 'Consanguinity'), ('M', 'Marriage')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Relationships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_relationship_started', models.DateField()),
                ('date_relationship_ended', models.DateField(blank=True, null=True)),
                ('relationship_place', models.CharField(blank=True, max_length=50, null=True)),
                ('other_relationship_details', models.TextField(blank=True, null=True)),
                ('family_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.Families')),
                ('individual_1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_1', to='family.Individuals')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_code', models.IntegerField(primary_key=True, serialize=False)),
                ('role_description', models.CharField(choices=[('F', 'Father'), ('M', 'Mother'), ('S', 'Son'), ('D', 'Daughter'), ('H', 'Husband'), ('W', 'Wife')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='relationships',
            name='individual_1_role_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_1_role', to='family.Roles'),
        ),
        migrations.AddField(
            model_name='relationships',
            name='individual_2_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_2', to='family.Individuals'),
        ),
        migrations.AddField(
            model_name='relationships',
            name='individual_2_role_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_2_role', to='family.Roles'),
        ),
        migrations.AddField(
            model_name='relationships',
            name='relationship_type_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.Relationship_Types'),
        ),
        migrations.AddField(
            model_name='families',
            name='head_of_family_individual_id',
            field=models.ManyToManyField(to='family.Individuals'),
        ),
    ]
