# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-26 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_auto_20190626_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='head_of_family_individual_id',
        ),
        migrations.AddField(
            model_name='family',
            name='head_of_family_individual_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='family.Individual'),
            preserve_default=False,
        ),
    ]
