# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-27 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import family.models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_auto_20190626_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individual',
            options={'ordering': ['date_of_birth']},
        ),
        migrations.AddField(
            model_name='individual',
            name='image_path',
            field=models.FileField(blank=True, null=True, upload_to=family.models.individual_directory_path),
        ),
    ]
