# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-28 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import family.models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0004_auto_20190627_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='image_path',
            field=models.FileField(blank=True, null=True, upload_to=family.models.family_directory_path),
        ),
    ]
