# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-05 02:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0006_auto_20190702_1053'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='individual',
            unique_together=set([('first_name', 'last_name')]),
        ),
    ]
