# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-05 03:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0007_auto_20190705_1000'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='individual',
            unique_together=set([]),
        ),
    ]
