# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-15 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0008_auto_20190705_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationship',
            options={'ordering': ['date_relationship_started']},
        ),
        migrations.AlterField(
            model_name='relationship_type',
            name='relationship_type_code',
            field=models.CharField(choices=[('C', 'Consanguinity'), ('M', 'Marriage')], max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='relationship_type',
            name='relationship_type_description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_code',
            field=models.CharField(choices=[('F', 'Father'), ('M', 'Mother'), ('S', 'Son'), ('D', 'Daughter'), ('H', 'Husband'), ('W', 'Wife')], max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_description',
            field=models.CharField(max_length=50),
        ),
    ]
