# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-16 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0009_auto_20190715_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
